name: vmtest

on:
  push:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Run main.sh on "default" kernel
      run: |
        uname -r

    - name: Run main.sh in specified kernel but with same userspace
      uses: danobi/vmtest-action@master
      with:
        kernel_url: https://github.com/fwilhe2/potential-spork/actions/runs/10656526510/artifacts/1879771762
        command: uname -r
